In [7]:
import numpy as np

In [8]:
a= np.array([1,2,3,4])

# To get dimension of an array
print(a.ndim)

#Get size
print(a.itemsize)

#Get total size
print(a.size)
print(a.size*a.itemsize/a.nbytes)
print(a.nbytes)


1
8
4
1.0
32


In [13]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
# To change any element
a[1,4]=15
a[:,3]=[16,17]
print(a)

[[ 1  2  3 16  5  6  7]
 [ 8  9 10 17 15 13 14]]


In [18]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b[0,1,1]
b[:,1,:]

#replace
b[:,1,:]=[[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


Creating Array

In [19]:
np.full_like(a,4)


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [20]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [23]:
np.random.randint(7,size=(3,3))

array([[6, 6, 1],
       [1, 1, 1],
       [4, 5, 3]], dtype=int32)

In [25]:
np.random.randint(4,7,size=(3,3))

array([[5, 5, 5],
       [6, 6, 4],
       [4, 6, 4]], dtype=int32)

In [27]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

To repeat an array

In [28]:
arr=np.array([1,2,3])
r1=np.repeat(arr,4,axis=0)
print(r1)

[1 1 1 1 2 2 2 2 3 3 3 3]


In [36]:
arr=np.array([[1,2,3]])
r2=np.repeat(arr,4,axis=0)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [39]:
arr=np.array([[[1,2,3]]])
r1=np.repeat(arr,4,axis=0)
print(r1)

[[[1 2 3]]

 [[1 2 3]]

 [[1 2 3]]

 [[1 2 3]]]


In [45]:
arr1=np.ones((5,5))
arr1[1:4,1:4]=0
arr1[2,2]=9
print(arr1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
