numpy arrays and basics 

In [3]:
import numpy as np 

creating arrays from list 

In [4]:
arr_1d = np.array([1,2,3,4,5])
print("1D array :" ,arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array :",arr_2d)

1D array : [1 2 3 4 5]
2D array : [[1 2 3]
 [4 5 6]]


List vs numpy array

In [5]:
py_list=[1,2,3,4,5]
print("python list multilication ",py_list * 2)

np_array=np.array([1,2,3,4])
print("python array multilication ",np_array * 2)


python list multilication  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
python array multilication  [2 4 6 8]


To check efficiency b\w list and numpy

In [6]:
import time 
start = time.time()
py_list= [i*2 for i in range(100000)]
print("\n list operation time :" , time.time()-start)

start = time.time()
np_array= np.arange(100000)*2
print("\n numpy operation time :", time.time()-start)


 list operation time : 0.04524040222167969

 numpy operation time : 0.0029757022857666016


creating array from scratch

In [7]:
zeros= np.zeros((3,5))
print("zeros array : \n",zeros)

ones= np.ones((2,1))
print("ones array : \n",ones)

full = np.full((4,4),3)
print("full array : \n",full)

random= np.random.random((1,3))
print("random array : \n",random)

sequence= np.arange(1,12,3)
print("sequence array : \n",sequence)


zeros array : 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
ones array : 
 [[1.]
 [1.]]
full array : 
 [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
random array : 
 [[0.02701916 0.55228812 0.41382414]]
sequence array : 
 [ 1  4  7 10]


Vector , Matrix and Tensor 

In [8]:
vector = np.array([1,2,3,4])
print("vector",vector)

matrix=np.array([[1,2,3],
                 [45,56,67],
                 [4,5,7]])
print("matrix \n" ,matrix)

tensor=np.array([[[1,2,3],[3,4,5]],
                 [[67,7,89],[4,8,90]]])
print("tensor",tensor)


vector [1 2 3 4]
matrix 
 [[ 1  2  3]
 [45 56 67]
 [ 4  5  7]]
tensor [[[ 1  2  3]
  [ 3  4  5]]

 [[67  7 89]
  [ 4  8 90]]]


Properties of array 

In [9]:
arr=np.array([[[1,2,3],
              [4,5,0],
              [8,9,0]]])

print("shape " , arr.shape)
print("dimension " , arr.ndim)
print("size " , arr.size)
print("dtype " , arr.dtype)


shape  (1, 3, 3)
dimension  3
size  9
dtype  int64


In [10]:
arr=np.array([[1,2,3],
              [4,5,0],
              [8,9,0]])

print("shape " , arr.shape)
print("dimension " , arr.ndim)

shape  (3, 3)
dimension  2


In [11]:
arr=np.array([1,2,3])

print("shape " , arr.shape)
print("dimension " , arr.ndim)

shape  (3,)
dimension  1


Array reshaping 

In [16]:
arr = np.arange(12)
print("Original array ",arr)

reshaped = arr.reshape((3,4))
print("reshaped array ", reshaped)

flattened = reshaped.flatten()
print("flattened array ", flattened)

raveled = reshaped.ravel()
print("ravel array",raveled)

transpose = reshaped.T
print("transpose array",transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravel array [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
