Numpy array operations 

In [22]:
import numpy as np 

In [23]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print('Basic Slicing',arr[2:7])
print("with step",arr[1:8:3])
print("negative indexing ",arr[-2])
print("negative indexing",arr[-3:-7:-1])


Basic Slicing [3 4 5 6 7]
with step [2 5 8]
negative indexing  8
negative indexing [7 6 5 4]


In [24]:
#For 2D array
arr_2d= np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print("specific element",arr_2d[1,2])
print("entire column",arr_2d[:,1])
print("entire row ",arr_2d[2])


specific element 6
entire column [2 5 8]
entire row  [7 8 9]


Sorting

In [25]:
unsorted = np.array([2,5,3,6,7,4,1,0])
print("sorted array",np.sort(unsorted))

arr_2d = np.array([[1,3],[2,1],[3,2]])
print("sorting of 2d array by column ",np.sort(arr_2d,axis =0))

arr_2d = np.array([[1,3],[2,1],[3,2]])
print("sorting of 2d array by row ",np.sort(arr_2d,axis =1))



sorted array [0 1 2 3 4 5 6 7]
sorting of 2d array by column  [[1 1]
 [2 2]
 [3 3]]
sorting of 2d array by row  [[1 3]
 [1 2]
 [2 3]]


Filter

In [26]:
numbers=np.array([1,2,3,4,5,6,7,8,9])
even_number=numbers[numbers%2==0]
print("even number ",even_number)

even number  [2 4 6 8]


In [27]:
numbers=np.array([1,2,3,4,5,6,7,8,9])
x= numbers%2==0
even_number=numbers[x]
print("even number ",even_number)

even number  [2 4 6 8]


In [28]:
#Filter with mask 
mask = numbers%2==0
print("even number ",numbers[mask])

even number  [2 4 6 8]


In [29]:
mask = numbers>5
print("numbers greater than 5 :",numbers[mask])

numbers greater than 5 : [6 7 8 9]


In [30]:
#index with list in numpy 
a= np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,5]]

array([2, 3, 6])

Fancy indexing Vs np.where()

In [31]:
indices=[0,2,4]
print(numbers[indices])

[1 3 5]


In [32]:
where_result = np.where(numbers>5)
print(where_result)
print(numbers[where_result])

(array([5, 6, 7, 8]),)
[6 7 8 9]


In [33]:
#condition array
condition_array=np.where(numbers>5,numbers*4,numbers)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36]


Adding and removing data 

In [34]:
arr1 = np.array([1,3,5])
arr2 = np.array([6,8,0])
arr3=np.array([2,4,7])
add = arr1+arr2 +arr3
print(add)

[ 9 15 12]


In [35]:
# to merge and concatenate
arr1 = np.array([1,3,5])
arr2 = np.array([6,8,0])
arr3=np.array([2,4,7])
combined= np.concatenate((arr1,arr2,arr3))
print(combined)

[1 3 5 6 8 0 2 4 7]


Array markdown 

In [36]:
arr1 = np.array([1,3,5])
arr2 = np.array([6,8,0])
arr3=np.array([[2,4,7],
               [2,3,5]])
print("compatibility shapes",arr1.shape==arr2.shape)
print("compatibility shapes",arr3.shape==arr2.shape)

compatibility shapes True
compatibility shapes False


In [37]:
#operations 
original=np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original,new_row))
print(original)
print("\n",with_new_row)

new_col=np.array([[5],[6]])
with_new_col =np.hstack((original,new_col))
print("\n",original)
print("\n",with_new_col)

[[1 2]
 [3 4]]

 [[1 2]
 [3 4]
 [5 6]]

 [[1 2]
 [3 4]]

 [[1 2 5]
 [3 4 6]]


Delete operations

In [38]:
arr=np.array([1,2,3,4,5])
deleted=np.delete(arr,3)
print("array after deletion:" , deleted)

array after deletion: [1 2 3 5]


In [39]:
arr=np.array([[1,2],
              [3,4],
              [5,6]])
deleted=np.delete(arr,1)
print(deleted)

[1 3 4 5 6]


In [40]:
arr=np.array([[1,2],
              [3,4],
              [5,6]])
deleted=np.delete(arr,1,axis=0)
print(deleted)

[[1 2]
 [5 6]]


In [41]:
arr=np.array([[[1,2],[4,3]],
              [[6,7],[8,9]]])
deleted=np.delete(arr,0,2)
print(deleted)

[[[2]
  [3]]

 [[7]
  [9]]]


In [42]:
arr=np.array([[[1,2],[4,3]],
              [[6,7],[8,9]]])
deleted=np.delete(arr,0,0)
print(deleted)

[[[6 7]
  [8 9]]]
